// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: executor.proto

package cn.shuangbofu.nocturne.protobuf;

public final class ExecutorProto {
  private ExecutorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ExecutorRegistryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ExecutorRegistry)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 groupId = 1;</code>
     * @return The groupId.
     */
    int getGroupId();
  }
  /**
   * <pre>
   * 执行器注册
   * </pre>
   *
   * Protobuf type {@code ExecutorRegistry}
   */
  public  static final class ExecutorRegistry extends
      com.google.protobuf.GeneratedMessageLite<
          ExecutorRegistry, ExecutorRegistry.Builder> implements
      // @@protoc_insertion_point(message_implements:ExecutorRegistry)
      ExecutorRegistryOrBuilder {
    private ExecutorRegistry() {
    }
    public static final int GROUPID_FIELD_NUMBER = 1;
    private int groupId_;
    /**
     * <code>int32 groupId = 1;</code>
     * @return The groupId.
     */
    @java.lang.Override
    public int getGroupId() {
      return groupId_;
    }
    /**
     * <code>int32 groupId = 1;</code>
     * @param value The groupId to set.
     */
    private void setGroupId(int value) {
      
      groupId_ = value;
    }
    /**
     * <code>int32 groupId = 1;</code>
     */
    private void clearGroupId() {
      
      groupId_ = 0;
    }

    public static cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * 执行器注册
     * </pre>
     *
     * Protobuf type {@code ExecutorRegistry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry, Builder> implements
        // @@protoc_insertion_point(builder_implements:ExecutorRegistry)
        cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistryOrBuilder {
      // Construct using cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 groupId = 1;</code>
       * @return The groupId.
       */
      @java.lang.Override
      public int getGroupId() {
        return instance.getGroupId();
      }
      /**
       * <code>int32 groupId = 1;</code>
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(int value) {
        copyOnWrite();
        instance.setGroupId(value);
        return this;
      }
      /**
       * <code>int32 groupId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        copyOnWrite();
        instance.clearGroupId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ExecutorRegistry)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "groupId_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry> parser = PARSER;
          if (parser == null) {
            synchronized (cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:ExecutorRegistry)
    private static final cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry DEFAULT_INSTANCE;
    static {
      ExecutorRegistry defaultInstance = new ExecutorRegistry();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ExecutorRegistry.class, defaultInstance);
    }

    public static cn.shuangbofu.nocturne.protobuf.ExecutorProto.ExecutorRegistry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ExecutorRegistry> PARSER;

    public static com.google.protobuf.Parser<ExecutorRegistry> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
