// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heart_beat.proto

package cn.shuangbofu.nocturne.protobuf;

public final class HeartBeatProto {
  private HeartBeatProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface HeartBeatRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string msg = 1;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 1;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>repeated uint64 tasks = 2;</code>
     * @return A list containing the tasks.
     */
    java.util.List<java.lang.Long> getTasksList();
    /**
     * <code>repeated uint64 tasks = 2;</code>
     * @return The count of tasks.
     */
    int getTasksCount();
    /**
     * <code>repeated uint64 tasks = 2;</code>
     * @param index The index of the element to return.
     * @return The tasks at the given index.
     */
    long getTasks(int index);
  }
  /**
   * <pre>
   *心跳
   * </pre>
   *
   * Protobuf type {@code HeartBeatRequest}
   */
  public  static final class HeartBeatRequest extends
      com.google.protobuf.GeneratedMessageLite<
          HeartBeatRequest, HeartBeatRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:HeartBeatRequest)
      HeartBeatRequestOrBuilder {
    private HeartBeatRequest() {
      msg_ = "";
      tasks_ = emptyLongList();
    }
    public static final int MSG_FIELD_NUMBER = 1;
    private java.lang.String msg_;
    /**
     * <code>string msg = 1;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      return msg_;
    }
    /**
     * <code>string msg = 1;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(msg_);
    }
    /**
     * <code>string msg = 1;</code>
     * @param value The msg to set.
     */
    private void setMsg(
        java.lang.String value) {
      value.getClass();
  
      msg_ = value;
    }
    /**
     * <code>string msg = 1;</code>
     */
    private void clearMsg() {
      
      msg_ = getDefaultInstance().getMsg();
    }
    /**
     * <code>string msg = 1;</code>
     * @param value The bytes for msg to set.
     */
    private void setMsgBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      msg_ = value.toStringUtf8();
      
    }

    public static final int TASKS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.LongList tasks_;
    /**
     * <code>repeated uint64 tasks = 2;</code>
     * @return A list containing the tasks.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getTasksList() {
      return tasks_;
    }
    /**
     * <code>repeated uint64 tasks = 2;</code>
     * @return The count of tasks.
     */
    @java.lang.Override
    public int getTasksCount() {
      return tasks_.size();
    }
    /**
     * <code>repeated uint64 tasks = 2;</code>
     * @param index The index of the element to return.
     * @return The tasks at the given index.
     */
    @java.lang.Override
    public long getTasks(int index) {
      return tasks_.getLong(index);
    }
    private int tasksMemoizedSerializedSize = -1;
    private void ensureTasksIsMutable() {
      com.google.protobuf.Internal.LongList tmp = tasks_;
      if (!tmp.isModifiable()) {
        tasks_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <code>repeated uint64 tasks = 2;</code>
     * @param index The index to set the value at.
     * @param value The tasks to set.
     */
    private void setTasks(
        int index, long value) {
      ensureTasksIsMutable();
      tasks_.setLong(index, value);
    }
    /**
     * <code>repeated uint64 tasks = 2;</code>
     * @param value The tasks to add.
     */
    private void addTasks(long value) {
      ensureTasksIsMutable();
      tasks_.addLong(value);
    }
    /**
     * <code>repeated uint64 tasks = 2;</code>
     * @param values The tasks to add.
     */
    private void addAllTasks(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureTasksIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, tasks_);
    }
    /**
     * <code>repeated uint64 tasks = 2;</code>
     */
    private void clearTasks() {
      tasks_ = emptyLongList();
    }

    public static cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     *心跳
     * </pre>
     *
     * Protobuf type {@code HeartBeatRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatRequest)
        cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequestOrBuilder {
      // Construct using cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string msg = 1;</code>
       * @return The msg.
       */
      @java.lang.Override
      public java.lang.String getMsg() {
        return instance.getMsg();
      }
      /**
       * <code>string msg = 1;</code>
       * @return The bytes for msg.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMsgBytes() {
        return instance.getMsgBytes();
      }
      /**
       * <code>string msg = 1;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        copyOnWrite();
        instance.setMsg(value);
        return this;
      }
      /**
       * <code>string msg = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        copyOnWrite();
        instance.clearMsg();
        return this;
      }
      /**
       * <code>string msg = 1;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMsgBytes(value);
        return this;
      }

      /**
       * <code>repeated uint64 tasks = 2;</code>
       * @return A list containing the tasks.
       */
      @java.lang.Override
      public java.util.List<java.lang.Long>
          getTasksList() {
        return java.util.Collections.unmodifiableList(
            instance.getTasksList());
      }
      /**
       * <code>repeated uint64 tasks = 2;</code>
       * @return The count of tasks.
       */
      @java.lang.Override
      public int getTasksCount() {
        return instance.getTasksCount();
      }
      /**
       * <code>repeated uint64 tasks = 2;</code>
       * @param index The index of the element to return.
       * @return The tasks at the given index.
       */
      @java.lang.Override
      public long getTasks(int index) {
        return instance.getTasks(index);
      }
      /**
       * <code>repeated uint64 tasks = 2;</code>
       * @param value The tasks to set.
       * @return This builder for chaining.
       */
      public Builder setTasks(
          int index, long value) {
        copyOnWrite();
        instance.setTasks(index, value);
        return this;
      }
      /**
       * <code>repeated uint64 tasks = 2;</code>
       * @param value The tasks to add.
       * @return This builder for chaining.
       */
      public Builder addTasks(long value) {
        copyOnWrite();
        instance.addTasks(value);
        return this;
      }
      /**
       * <code>repeated uint64 tasks = 2;</code>
       * @param values The tasks to add.
       * @return This builder for chaining.
       */
      public Builder addAllTasks(
          java.lang.Iterable<? extends java.lang.Long> values) {
        copyOnWrite();
        instance.addAllTasks(values);
        return this;
      }
      /**
       * <code>repeated uint64 tasks = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTasks() {
        copyOnWrite();
        instance.clearTasks();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HeartBeatRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "msg_",
              "tasks_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u0208\u0002&";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest> parser = PARSER;
          if (parser == null) {
            synchronized (cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:HeartBeatRequest)
    private static final cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest DEFAULT_INSTANCE;
    static {
      HeartBeatRequest defaultInstance = new HeartBeatRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        HeartBeatRequest.class, defaultInstance);
    }

    public static cn.shuangbofu.nocturne.protobuf.HeartBeatProto.HeartBeatRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<HeartBeatRequest> PARSER;

    public static com.google.protobuf.Parser<HeartBeatRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
