// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.shuangbofu.nocturne.protobuf;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.MessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.MessageType type = 1;</code>
     * @return The type.
     */
    cn.shuangbofu.nocturne.protobuf.MessageTypeProto.MessageType getType();

    /**
     * <code>sint32 reqId = 2;</code>
     * @return The reqId.
     */
    int getReqId();

    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageLite<
          Message, Message.Builder> implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
    private Message() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.MessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.MessageType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public cn.shuangbofu.nocturne.protobuf.MessageTypeProto.MessageType getType() {
      cn.shuangbofu.nocturne.protobuf.MessageTypeProto.MessageType result = cn.shuangbofu.nocturne.protobuf.MessageTypeProto.MessageType.forNumber(type_);
      return result == null ? cn.shuangbofu.nocturne.protobuf.MessageTypeProto.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.MessageType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     */
    private void setTypeValue(int value) {
        type_ = value;
    }
    /**
     * <code>.MessageType type = 1;</code>
     * @param value The type to set.
     */
    private void setType(cn.shuangbofu.nocturne.protobuf.MessageTypeProto.MessageType value) {
      type_ = value.getNumber();
      
    }
    /**
     * <code>.MessageType type = 1;</code>
     */
    private void clearType() {
      
      type_ = 0;
    }

    public static final int REQID_FIELD_NUMBER = 2;
    private int reqId_;
    /**
     * <code>sint32 reqId = 2;</code>
     * @return The reqId.
     */
    @java.lang.Override
    public int getReqId() {
      return reqId_;
    }
    /**
     * <code>sint32 reqId = 2;</code>
     * @param value The reqId to set.
     */
    private void setReqId(int value) {
      
      reqId_ = value;
    }
    /**
     * <code>sint32 reqId = 2;</code>
     */
    private void clearReqId() {
      
      reqId_ = 0;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 3;</code>
     * @param value The data to set.
     */
    private void setData(com.google.protobuf.ByteString value) {
      value.getClass();
  
      data_ = value;
    }
    /**
     * <code>bytes data = 3;</code>
     */
    private void clearData() {
      
      data_ = getDefaultInstance().getData();
    }

    public static cn.shuangbofu.nocturne.protobuf.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.shuangbofu.nocturne.protobuf.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.shuangbofu.nocturne.protobuf.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.MessageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.shuangbofu.nocturne.protobuf.MessageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.MessageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cn.shuangbofu.nocturne.protobuf.MessageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static cn.shuangbofu.nocturne.protobuf.MessageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cn.shuangbofu.nocturne.protobuf.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(cn.shuangbofu.nocturne.protobuf.MessageProto.Message prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          cn.shuangbofu.nocturne.protobuf.MessageProto.Message, Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        cn.shuangbofu.nocturne.protobuf.MessageProto.MessageOrBuilder {
      // Construct using cn.shuangbofu.nocturne.protobuf.MessageProto.Message.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.MessageType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override
      public int getTypeValue() {
        return instance.getTypeValue();
      }
      /**
       * <code>.MessageType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        copyOnWrite();
        instance.setTypeValue(value);
        return this;
      }
      /**
       * <code>.MessageType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public cn.shuangbofu.nocturne.protobuf.MessageTypeProto.MessageType getType() {
        return instance.getType();
      }
      /**
       * <code>.MessageType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setType(cn.shuangbofu.nocturne.protobuf.MessageTypeProto.MessageType value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>.MessageType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <code>sint32 reqId = 2;</code>
       * @return The reqId.
       */
      @java.lang.Override
      public int getReqId() {
        return instance.getReqId();
      }
      /**
       * <code>sint32 reqId = 2;</code>
       * @param value The reqId to set.
       * @return This builder for chaining.
       */
      public Builder setReqId(int value) {
        copyOnWrite();
        instance.setReqId(value);
        return this;
      }
      /**
       * <code>sint32 reqId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqId() {
        copyOnWrite();
        instance.clearReqId();
        return this;
      }

      /**
       * <code>bytes data = 3;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <code>bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Message)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new cn.shuangbofu.nocturne.protobuf.MessageProto.Message();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "type_",
              "reqId_",
              "data_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\f\u0002\u000f" +
                "\u0003\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<cn.shuangbofu.nocturne.protobuf.MessageProto.Message> parser = PARSER;
          if (parser == null) {
            synchronized (cn.shuangbofu.nocturne.protobuf.MessageProto.Message.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<cn.shuangbofu.nocturne.protobuf.MessageProto.Message>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Message)
    private static final cn.shuangbofu.nocturne.protobuf.MessageProto.Message DEFAULT_INSTANCE;
    static {
      Message defaultInstance = new Message();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Message.class, defaultInstance);
    }

    public static cn.shuangbofu.nocturne.protobuf.MessageProto.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Message> PARSER;

    public static com.google.protobuf.Parser<Message> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
