// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_type.proto

package cn.shuangbofu.nocturne.protobuf;

public final class MessageTypeProto {
  private MessageTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>response = 0;</code>
     */
    response(0),
    /**
     * <code>heartBeat = 1;</code>
     */
    heartBeat(1),
    /**
     * <code>executorRegistry = 2;</code>
     */
    executorRegistry(2),
    /**
     * <code>submitTaskRequest = 3;</code>
     */
    submitTaskRequest(3),
    /**
     * <code>submitTaskResponse = 4;</code>
     */
    submitTaskResponse(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>response = 0;</code>
     */
    public static final int response_VALUE = 0;
    /**
     * <code>heartBeat = 1;</code>
     */
    public static final int heartBeat_VALUE = 1;
    /**
     * <code>executorRegistry = 2;</code>
     */
    public static final int executorRegistry_VALUE = 2;
    /**
     * <code>submitTaskRequest = 3;</code>
     */
    public static final int submitTaskRequest_VALUE = 3;
    /**
     * <code>submitTaskResponse = 4;</code>
     */
    public static final int submitTaskResponse_VALUE = 4;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return response;
        case 1: return heartBeat;
        case 2: return executorRegistry;
        case 3: return submitTaskRequest;
        case 4: return submitTaskResponse;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            @java.lang.Override
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return MessageTypeVerifier.INSTANCE;
    }

    private static final class MessageTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new MessageTypeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return MessageType.forNumber(number) != null;
            }
          };

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageType)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
