// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web/web.proto

package cn.shuangbofu.nocturne.protobuf;

public final class WebServerProto {
  private WebServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface WebServerRegistryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WebServerRegistry)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string serverKey = 1;</code>
     * @return The serverKey.
     */
    java.lang.String getServerKey();
    /**
     * <code>string serverKey = 1;</code>
     * @return The bytes for serverKey.
     */
    com.google.protobuf.ByteString
        getServerKeyBytes();
  }
  /**
   * <pre>
   * web服务注册
   * </pre>
   *
   * Protobuf type {@code WebServerRegistry}
   */
  public  static final class WebServerRegistry extends
      com.google.protobuf.GeneratedMessageLite<
          WebServerRegistry, WebServerRegistry.Builder> implements
      // @@protoc_insertion_point(message_implements:WebServerRegistry)
      WebServerRegistryOrBuilder {
    private WebServerRegistry() {
      serverKey_ = "";
    }
    public static final int SERVERKEY_FIELD_NUMBER = 1;
    private java.lang.String serverKey_;
    /**
     * <code>string serverKey = 1;</code>
     * @return The serverKey.
     */
    @java.lang.Override
    public java.lang.String getServerKey() {
      return serverKey_;
    }
    /**
     * <code>string serverKey = 1;</code>
     * @return The bytes for serverKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServerKeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(serverKey_);
    }
    /**
     * <code>string serverKey = 1;</code>
     * @param value The serverKey to set.
     */
    private void setServerKey(
        java.lang.String value) {
      value.getClass();
  
      serverKey_ = value;
    }
    /**
     * <code>string serverKey = 1;</code>
     */
    private void clearServerKey() {
      
      serverKey_ = getDefaultInstance().getServerKey();
    }
    /**
     * <code>string serverKey = 1;</code>
     * @param value The bytes for serverKey to set.
     */
    private void setServerKeyBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      serverKey_ = value.toStringUtf8();
      
    }

    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * web服务注册
     * </pre>
     *
     * Protobuf type {@code WebServerRegistry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry, Builder> implements
        // @@protoc_insertion_point(builder_implements:WebServerRegistry)
        cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistryOrBuilder {
      // Construct using cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string serverKey = 1;</code>
       * @return The serverKey.
       */
      @java.lang.Override
      public java.lang.String getServerKey() {
        return instance.getServerKey();
      }
      /**
       * <code>string serverKey = 1;</code>
       * @return The bytes for serverKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getServerKeyBytes() {
        return instance.getServerKeyBytes();
      }
      /**
       * <code>string serverKey = 1;</code>
       * @param value The serverKey to set.
       * @return This builder for chaining.
       */
      public Builder setServerKey(
          java.lang.String value) {
        copyOnWrite();
        instance.setServerKey(value);
        return this;
      }
      /**
       * <code>string serverKey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerKey() {
        copyOnWrite();
        instance.clearServerKey();
        return this;
      }
      /**
       * <code>string serverKey = 1;</code>
       * @param value The bytes for serverKey to set.
       * @return This builder for chaining.
       */
      public Builder setServerKeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setServerKeyBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:WebServerRegistry)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "serverKey_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry> parser = PARSER;
          if (parser == null) {
            synchronized (cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:WebServerRegistry)
    private static final cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry DEFAULT_INSTANCE;
    static {
      WebServerRegistry defaultInstance = new WebServerRegistry();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        WebServerRegistry.class, defaultInstance);
    }

    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerRegistry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<WebServerRegistry> PARSER;

    public static com.google.protobuf.Parser<WebServerRegistry> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface WebServerHeartbeatRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WebServerHeartbeatRequest)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code WebServerHeartbeatRequest}
   */
  public  static final class WebServerHeartbeatRequest extends
      com.google.protobuf.GeneratedMessageLite<
          WebServerHeartbeatRequest, WebServerHeartbeatRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:WebServerHeartbeatRequest)
      WebServerHeartbeatRequestOrBuilder {
    private WebServerHeartbeatRequest() {
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code WebServerHeartbeatRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:WebServerHeartbeatRequest)
        cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequestOrBuilder {
      // Construct using cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:WebServerHeartbeatRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = null;java.lang.String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest> parser = PARSER;
          if (parser == null) {
            synchronized (cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:WebServerHeartbeatRequest)
    private static final cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest DEFAULT_INSTANCE;
    static {
      WebServerHeartbeatRequest defaultInstance = new WebServerHeartbeatRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        WebServerHeartbeatRequest.class, defaultInstance);
    }

    public static cn.shuangbofu.nocturne.protobuf.WebServerProto.WebServerHeartbeatRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<WebServerHeartbeatRequest> PARSER;

    public static com.google.protobuf.Parser<WebServerHeartbeatRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
